branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: gp6X8L+IeDxs6W/vwSXqTNTf3Y0qIaakwIxXmOSIF8lkdp0beNHB3d967tdTCE9ZbS7+beLXTlTvdF+ramxWaNCiq5V/cAomVw07arqQBMx35jyDxEOVQScHje+RNMLqtJjKE1Ik6wNxR+6jZsUyHHFzHD03e9aoTswpBFr4nE37rmjNsUTF249l7Tz/JhG+VhwBF2jULFElvzcQXnqE7sGYeQuPO1Qms1dZOLnpoAS1gHA+vBxSkiquJ9+Pk92FPTfhiY/yC9ZVtW/vnsgGalKkJZGBCl15aQbSPJmEIB41Ewn+g/AhH9sR6xKOQ9SBFIV7HE0Zzp2advrVBLjoBCbr9B9I3phx6Jn56J9rXBXYh64T6ZGjXOny63o3+nImQI3Li7/T36C/iEnR2IbAEEfRgdFSwfy93Qhd0ZCGuTlWMR/BnWbcxt0yzGWzxdVKWln4Ot8ljZWfku7jSVhdVGMoJIztIT9/RdckKEJj59aTjSfNt/KmIJNTUDNfM2dlpJxTk0iWa6FaYk+14N+4J2JXMow7ZkyQ1vJlKxCN1MwqmBi6HI6f3plCWL/LtOF7aKuuYsO2GM1LmB6LKVKWhXmRBii2q5I80kjfOLGJgTK3G/UmywIy+GbEXA+sUjJvDdFFBidTCj95zinV16PrSWhk2Pe/z8XaEffcWJco2CU=
  project: cf-booth-map
cache:
  yarn: true
